const MEMBERS = [
  {
    name: '경민서',
    title: '컴퓨터과학 21',
    position: '회장',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
      velog: 'https://velog.com/username',
      tstory: 'https://tstory.com/username',
    },
    answers: [
      '안녕하세요, 저는 경민서입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '정지원',
    title: '컴퓨터과학 21',
    position: '부회장',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
      velog: 'https://velog.com/username',
    },
    answers: [
      '안녕하세요, 저는 정지원입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '류미성',
    title: '컴퓨터과학 21',
    position: '프론트엔드장',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 류미성입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '주아정',
    title: '컴퓨터과학 21',
    position: '백엔드장',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 주아정입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '윤현서',
    title: '컴퓨터과학 21',
    position: '10기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 윤현서입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '이지은',
    title: '컴퓨터과학 21',
    position: '10기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 이지은입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '이해림',
    title: '컴퓨터과학 21',
    position: '10기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 이해림입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '정서연',
    title: '컴퓨터과학 21',
    position: '10기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 정서연입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '김혜림',
    title: '컴퓨터과학 21',
    position: '10.5기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 김혜림입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '하예영',
    title: '컴퓨터과학 21',
    position: '10.5기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 하예영입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '권유진',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 권유진입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '김준희',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 김준희입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '김지민',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 김지민입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '방지희',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 방지희입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '백수민',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 백수민입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '신정은',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 신정은입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '유하연',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 유하연입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '윤서빈',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 윤서빈입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '윤정란',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 윤정란입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },

  {
    name: '윤지원',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 윤지원입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '이다빈',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 이다빈입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '하지민',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 하지민입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
  {
    name: '홍연주',
    title: '컴퓨터과학 21',
    position: '11기',
    image: 'ryumisung.png',
    techStack: ['React', 'Next.js', 'TypeScript'],
    snsLinks: {
      github: 'https://github.com/username',
      linkedin: 'https://linkedin.com/in/username',
    },
    answers: [
      '안녕하세요, 저는 홍연주입니다!',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다.',
      '좋은 팀원들을 만나 재밌게 프로젝트를 한 1달이 제일 기억 납니다. ',
    ],
  },
];

export default MEMBERS;
